# === Memory / VM ===
# Eliminasi background compaction stalls (THP=madvise sudah optimal)
vm.compaction_proactiveness = 0

# Memory reclaim lebih responsif untuk zram (default 10 → 125) catatan: 175 dipakai jika menerapkan lru_marie
vm.watermark_scale_factor = 175
# swappiness di-set 1 JIKA menggunakan lru_marie (artinya prioritas anonymous pages tetap di RAM, tidak mudah dibuang). set 150 jika ga pakai lru_marie
vm.swappiness = 150

kernel.numa_balancing = 0
